CREATE DATABASE AUTHENTICATION
USE AUTHENTICATION

CREATE TABLE INFORMATION(
    sUSERNAME VARCHAR(255) PRIMARY KEY,
    sPASSWORD VARCHAR(255)
)

SELECT *
FROM INFORMATION

DELETE FROM INFORMATION
WHERE sUSERNAME = 'danh' or sUSERNAME = 'uwu'

INSERT INTO INFORMATION
VALUES ('admin', 'admin')
